config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  # includes
  # includes
  # has_paper_trail
  # acts_as_paranoid

  # before_save
  # after_save

  # belongs_to
  # belongs_to
  # belongs_to
  # belongs_to
  # has_many
  # has_many
  # has_many
  # has_many
  # has_one

  # scope
  # scope

  # validates
  # validates
  # validates

  # extend enumerize
  # enumerize :sometype, in: [:type_1, :type_2]
  # enumerize :other_type, in: [:other_2, :other_2]

  # def domain_logic
  #     ...
  # end

  # def domain_logic
  #     ...
  # end

  # def domain_logic
  #     ...
  # end

  # def view_logic
  #     ...
  # end

  def display_name
    "#{name} the #{breed}"
  end
end

app/models/user.rb
class User < ApplicationRecord
    def name
        "#{first_name} #{last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    # @pet_presenters = PetPresenter.prepare(Pet.all, view_context)
    # @pet_presenters = Pet.all.map { |pet| PetPresenter.new(pet, view_context) }
    @pets_presenter = PetPresenter::Collection.new(Pet.all, view_context)
  end

  def show
    @pet_presenter = PetPresenter.new(Pet.find(params[:id]), view_context)
  end

  def new
    @pet = Pet.new
  end

  def edit
  end

  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to @pet, notice: 'Pet was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pet.update(pet_params)
      redirect_to @pet, notice: 'Pet was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_url, notice: 'Pet was successfully destroyed.'
  end

  private
    def set_pet
      @pet = Pet.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :breed, :age)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
  def self.display_name(pet)
    "#{pet.name} the #{pet.breed}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_name(user)
    "#{user.first_name} #{user.last_name}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrisrubyPresenters</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </p>
  <p>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets_presenter.each do |pet| %>
      <tr>
        <td><%= pet.name %> <%= pet.breed %></td>
        <td><%= PetsHelper.display_name(pet) %></td>
        <td><%= pet.display_name %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @pet.display_name %></h1>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %>
        <td><%= user.first_name %> <%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>